version: "3.9"

services:
    api:
        build:
            context: .
            dockerfile: ./docker/local/django/Dockerfile
        command: /start
        volumes:
          - .:/app
          - static_volume:/app/staticfiles 
          - media_volume:/app/mediafiles
        ports:
          - 8000:8000
        env_file:
          - .env
        depends_on:
          - postgres-db
        networks:
          - react-estate

    postgres-db:
        container_name: ${PG_HOST}
        image: postgres:13-alpine3.16
        restart: always
        ports:
          - "5432:5432"
        command: postgres
        expose:
        - 5432
        volumes:
          - postgres_data:/var/lib/postgresql/data/
        environment:
          - POSTGRES_USER='postgres'
          - POSTGRES_PASSWORD='Kabyle2022'
          - POSTGRES_DB='RealEstate'
        networks:
            - react-estate
networks:
    react-estate:
        driver: bridge

volumes:
    postgres_data:
    static_volume:
    media_volume:
